#!/bin/bash
project_root=$(dirname $(dirname "$0"))
cd $project_root
project_root=$(pwd)

rm -rf $project_root/bin

cd $project_root/Tools/BuildSystem/EntityBuilder
dotnet publish

cd $project_root
mkdir -p bin/src/EntityBuilder
cp -r Tools/BuildSystem/EntityBuilder/bin/Release/net9.0/publish/* bin/src/EntityBuilder
ln -s src/EntityBuilder/EntityBuilder bin/EntityBuilder

# renderer module: material builder
cd $project_root/Engine/RendererModule/Tools/MaterialEditor/MaterialBuilder
dotnet publish
cd $project_root
mkdir -p bin/src/MaterialBuilder
cp -r Engine/RendererModule/Tools/MaterialEditor/MaterialBuilder/bin/Release/net9.0/publish/* bin/src/MaterialBuilder
ln -s src/MaterialBuilder/MaterialBuilder bin/MaterialBuilder

# renderer module: pipeline builder
cd $project_root/Engine/RendererModule/Tools/MaterialEditor/PipelineBuilder
dotnet publish
cd $project_root
mkdir -p bin/src/PipelineBuilder
cp -r Engine/RendererModule/Tools/MaterialEditor/PipelineBuilder/bin/Release/net9.0/publish/* bin/src/PipelineBuilder
ln -s src/PipelineBuilder/PipelineBuilder bin/PipelineBuilder
